# 部署 Vue.js 简历网站到 GitHub Pages
name: Deploy Resume Site to Pages

on:
  # 在推送到 main 分支时运行
  push:
    branches: ["main"]
    paths:
      - "resume-site/**"
      - ".github/workflows/deploy-resume.yml"

  # 允许从 Actions 标签页手动运行
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

# 默认使用 bash
defaults:
  run:
    shell: bash

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: resume-site/package-lock.json

      - name: 安装依赖
        run: |
          cd resume-site
          npm ci

      - name: 构建项目
        run: |
          cd resume-site
          npm run build

      - name: 设置 Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: 准备部署文件
        run: |
          # 将构建的文件移动到根目录
          cp -r resume-site/dist/* ./
          # 创建 .nojekyll 文件以避免 Jekyll 处理
          touch .nojekyll

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
